### ISSUE TITLE
Fatal error.

### ISSUE THREAD

**Issue by mirkodn** [robertstaddon/buddypress-woocommerce#1]
Hi Robert, thank you for taking the time to find a good solution to integrate buddypress with woocommerce. This plugin would be the perfect solution for many people like myself that need to make work an online community with an e-store. 
I would love to have the skills to help you out with this, unfortunately my coding experience are really basic. 

I am providing you with the error that i get when activating your plugin with the hope that you could find a solution.

best,
Mirko 

Plugin could not be activated because it triggered a fatal error.

Fatal error: Cannot redeclare is_add_payment_method_page() (previously declared in /home/train2create/public_html/wp-content/plugins/woocommerce/includes/wc-conditional-functions.php:209) in /home/train2create/public_html/wp-content/plugins/buddypress-woocommerce-master/buddypress-woocommerce.php on line 25

**Comment by robertstaddon** [comment]
@mirkodn, I just made a commit that should solve your problem: https://github.com/robertstaddon/buddypress-woocommerce/commit/dfa5e10e19e45e4db5b60550f9b30486b1fb61f5

Can you try re-installing this plugin with the latest version and trying again?

**Comment by mirkodn** [comment]
Hi @robertstaddon , thank you for your prompt reply.
It works now, My woocommerce account info are now available in buddypress.  :) 

I would like to ask you if you are planning to develop this plug in further?

best,
Mirko

**Comment by robertstaddon** [comment]
I'm glad it's working now, @mirkodn!

What further features would you like to see in the plugin?
