### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by gfirem** [robertstaddon/buddypress-woocommerce#2]
Hi, it not work! Please help me!

**Comment by robertstaddon** [comment]
I'm sorry that it's not working for you. Can you explain what kind of problem that you're having?

**Comment by gfirem** [comment]
Thanks for your answer, i install the plugins and dont see any changes into the buddypress profile. I star coding for my own, but i will appreciate your help. I Am trying to integrate woocommerce my account into BP i am trying with the themekraft plugins, but i face a big wall.

**Comment by robertstaddon** [comment]
If you have the latest version of BuddyPress and WooCommerce installed as well as this plugin, you should see a new "Account" tab in the BuddyPress account panel. If you turn on WP_DEBUG, are you getting any errors?

**Comment by gfirem** [comment]
Let me check. I dont see anything i disable the themekraft plugins, update woo and Bp and i dont see anything.  I clear the permalinks to

**Comment by robertstaddon** [comment]
Did you figure out anything, @gfirem ?

**Comment by gfirem** [comment]
Hi there, sorry i forget to answer you. Finally i use the themekraft new version and it work.
