### ISSUE TITLE
Text-domain plugin and own pot file

### ISSUE THREAD

**Issue by alexanderdejong** [robertstaddon/buddypress-woocommerce#5]
Great plugin, I just noticed your using the same textdomain as buddypress. In your next update could you give it its own pot file and textdomain so we can easily translate your plugin?

**Comment by robertstaddon** [comment]
Thank you for reporting this, @alexanderdejong! 

I just made a commit that should fix this issue? https://github.com/robertstaddon/buddypress-woocommerce/commit/484bd9192dd468f879d9dcd15c458ba627b6573b
